server:
  name: "GoBackend"
  profile: dev
  trustedProxies:
    - 127.0.0.1
  port: 8080
  version: 1.0.0

databases:
  mysql:
    host: localhost
    port: 3306
    username: admin
    password: secret
    schema:
      - mydatabase
  postgresql:
    host: localhost
    port: 5432
    username: admin111
    password: secret222
    schema:
      - mydatabase333

logger:
  logLevel: debug
  fileName: ./log
  maxSize: 10
  maxBackup: 3
  maxAge: 28
  compress: true
