server:
  name: GoBackend
  profile: dev
  trustedProxies:
    - 127.0.0.1
  port: :8089
  version: 1.0.0
  timezone: Asia/Ho_Chi_Minh
  clientTimeout: 30
  serverTimeout: 30

databases:
  - driver: sqlserver
    host: localhost
    port: 1433
    username: admin
    password: secret
    schema:
      - mydatabase
  - driver: postgresql
    host: localhost
    port: 5432
    username: admin111
    password: secret222
    schema:
      - mydatabase333
  - driver: godror
    host: localhost
    port: 5432
    username: admin111
    password: secret222
    schema:
      - mydatabase333

logger:
  isSplit: false
  cronTime: 0 0 * * *
  logAppDir: ./logs/app
  logRRDir: ./logs/req_res
  logExtDir: ./logs/ext
  maxSize: 5
  maxBackup: 3
  maxAge: 28
  compress: true
